! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-2.1 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : cbmz_mosaic_8bin_vbs9_Monitor.f90
! Time                 : Mon Feb 27 11:08:27 2017
! Working directory    : /data/ksetigui/setigui/WRFV3_171015/chem/KPP/mechanisms/cbmz_mosaic_8bin_vbs9
! Equation file        : cbmz_mosaic_8bin_vbs9.kpp
! Output root filename : cbmz_mosaic_8bin_vbs9
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE cbmz_mosaic_8bin_vbs9_Monitor


  CHARACTER(LEN=12), PARAMETER, DIMENSION(90) :: SPC_NAMES_0 = (/ &
     'H2SO4       ','HCl         ','NH3         ', &
     'PCG1_B_C    ','PCG1_B_O    ','PCG1_F_C    ', &
     'PCG1_F_O    ','HCOOH       ','RCOOH       ', &
     'ARO1        ','ARO2        ','ALK1        ', &
     'OLE1        ','API1        ','API2        ', &
     'LIM1        ','LIM2        ','PSD1        ', &
     'PSD2        ','PCG2_B_O    ','PCG3_B_O    ', &
     'PCG4_B_O    ','PCG5_B_O    ','PCG6_B_O    ', &
     'PCG7_B_O    ','PCG8_B_O    ','PCG9_B_O    ', &
     'PCG2_F_O    ','PCG3_F_O    ','PCG4_F_O    ', &
     'PCG5_F_O    ','PCG6_F_O    ','PCG7_F_O    ', &
     'PCG8_F_O    ','PCG9_F_O    ','O1D         ', &
     'SO2         ','PCG2_B_C    ','OPCG1_B_C   ', &
     'PCG3_B_C    ','PCG4_B_C    ','PCG5_B_C    ', &
     'PCG6_B_C    ','PCG7_B_C    ','PCG8_B_C    ', &
     'PCG9_B_C    ','OPCG8_B_O   ','ANOL        ', &
     'OPCG8_B_C   ','OPCG7_B_O   ','OPCG7_B_C   ', &
     'OPCG6_B_O   ','OPCG6_B_C   ','OPCG5_B_O   ', &
     'OPCG5_B_C   ','OPCG4_B_O   ','OPCG4_B_C   ', &
     'OPCG3_B_O   ','OPCG3_B_C   ','OPCG2_B_C   ', &
     'OPCG1_B_O   ','OPCG2_B_O   ','PCG2_F_C    ', &
     'OPCG1_F_C   ','PCG3_F_C    ','PCG4_F_C    ', &
     'PCG5_F_C    ','PCG6_F_C    ','PCG7_F_C    ', &
     'PCG8_F_C    ','PCG9_F_C    ','OPCG8_F_O   ', &
     'OPCG8_F_C   ','OPCG7_F_O   ','OPCG7_F_C   ', &
     'OPCG6_F_O   ','OPCG6_F_C   ','OPCG5_F_O   ', &
     'OPCG5_F_C   ','OPCG4_F_O   ','OPCG4_F_C   ', &
     'OPCG3_F_O   ','OPCG3_F_C   ','OPCG2_F_C   ', &
     'OPCG1_F_O   ','OPCG2_F_O   ','PAN         ', &
     'H2O2        ','TOL         ','N2O5        ' /)
  CHARACTER(LEN=12), PARAMETER, DIMENSION(48) :: SPC_NAMES_1 = (/ &
     'XYL         ','CRO         ','CH4         ', &
     'API         ','LIM         ','HNO4        ', &
     'TO2         ','C2H6        ','XPAR        ', &
     'CH3OOH      ','ETHOOH      ','HONO        ', &
     'ETH         ','CH3OH       ','CRES        ', &
     'O3P         ','HNO3        ','CO          ', &
     'PAR         ','OPEN        ','ISOPN       ', &
     'ISOPO2      ','ISOPP       ','OLET        ', &
     'ISOP        ','HCHO        ','XO2         ', &
     'AONE        ','OLEI        ','NAP         ', &
     'MGLY        ','ETHP        ','ALD2        ', &
     'CH3O2       ','ISOPRD      ','ONIT        ', &
     'O3          ','RO2         ','NO2         ', &
     'C2O3        ','OH          ','HO2         ', &
     'NO          ','ANO2        ','ROOH        ', &
     'NO3         ','H2O         ','M           ' /)
  CHARACTER(LEN=12), PARAMETER, DIMENSION(138) :: SPC_NAMES = (/&
    SPC_NAMES_0, SPC_NAMES_1 /)

  INTEGER, DIMENSION(1) :: LOOKAT
  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=12), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_0 = (/ &
     '           NO2 --> O3P + NO                                                                         ', &
     '           NO3 --> 0.89 O3P + 0.89 NO2 + 0.11 NO                                                    ', &
     '          HONO --> OH + NO                                                                          ', &
     '          HNO3 --> NO2 + OH                                                                         ', &
     '          HNO4 --> NO2 + HO2                                                                        ', &
     '          N2O5 --> NO2 + NO3                                                                        ', &
     '            O3 --> O3P                                                                              ', &
     '            O3 --> O1D                                                                              ', &
     '          H2O2 --> 2 OH                                                                             ', &
     '          HCHO --> CO + 2 HO2                                                                       ', &
     '          HCHO --> CO                                                                               ', &
     '        CH3OOH --> HCHO + OH + HO2                                                                  ', &
     '        ETHOOH --> ALD2 + OH + HO2                                                                  ', &
     '          ALD2 --> CO + CH3O2 + HO2                                                                 ', &
     '          AONE --> CH3O2 + C2O3                                                                     ', &
     '          MGLY --> CO + C2O3 + HO2                                                                  ', &
     '          OPEN --> CO + C2O3 + HO2                                                                  ', &
     '          ROOH --> 1.98 XPAR + 0.4 XO2 + 0.74 AONE + 0.1 ETHP + 0.3 ALD2 + OH + 0.9 HO2             ', &
     '          ONIT --> 1.98 XPAR + 0.41 XO2 + 0.74 AONE + 0.1 ETHP + 0.3 ALD2 + NO2 + 0.9 HO2           ', &
     '        ISOPRD --> 0.33 CO + 0.2 HCHO + 0.03 AONE + 0.07 ALD2 + 0.7 CH3O2 + 0.97 C2O3 + 0.33 HO2    ', &
     '       O1D + M --> O3P                                                                              ', &
     '     O1D + H2O --> 2 OH                                                                             ', &
     '       O3P + M --> O3                                                                               ', &
     '      O3P + O3 --> 0.42 M                                                                           ', &
     '     O3P + NO2 --> NO                                                                               ', &
     '     O3P + NO2 --> NO3                                                                              ', &
     '      O3P + NO --> NO2                                                                              ', &
     '       O3 + NO --> NO2                                                                              ', &
     '      O3 + NO2 --> NO3                                                                              ', &
     '       O3 + OH --> PSD1 + HO2                                                                       ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_1 = (/ &
     '      O3 + HO2 --> OH                                                                               ', &
     '        OH + M --> PSD1 + HO2 + H2O                                                                 ', &
     '       OH + NO --> PSD1 + HONO                                                                      ', &
     '      NO2 + OH --> PSD1 + HNO3                                                                      ', &
     '      OH + NO3 --> PSD1 + NO2 + HO2                                                                 ', &
     '     HONO + OH --> PSD1 + NO2                                                                       ', &
     '     HNO3 + OH --> PSD1 + NO3                                                                       ', &
     '     HNO4 + OH --> PSD1 + NO2                                                                       ', &
     '      OH + HO2 --> PSD1 + H2O + 0.21 M                                                              ', &
     '     H2O2 + OH --> PSD1 + HO2                                                                       ', &
     '         2 HO2 --> H2O2                                                                             ', &
     '   2 HO2 + H2O --> H2O2                                                                             ', &
     '      HO2 + NO --> NO2 + OH                                                                         ', &
     '     NO2 + HO2 --> HNO4                                                                             ', &
     '     NO2 + HO2 --> HONO                                                                             ', &
     '          HNO4 --> NO2 + HO2                                                                        ', &
     '      NO + NO3 --> 2 NO2                                                                            ', &
     '     NO2 + NO3 --> NO2 + NO                                                                         ', &
     '     NO2 + NO3 --> N2O5                                                                             ', &
     '         2 NO3 --> 2 NO2                                                                            ', &
     '     HO2 + NO3 --> 0.3 HNO3 + 0.7 NO2 + 0.7 OH                                                      ', &
     '    N2O5 + H2O --> 2 HNO3                                                                           ', &
     '          N2O5 --> NO2 + NO3                                                                        ', &
     '       CO + OH --> PSD1 + HO2                                                                       ', &
     '      SO2 + OH --> H2SO4 + PSD1 + HO2                                                               ', &
     '      CH4 + OH --> PSD1 + CH3O2                                                                     ', &
     '     C2H6 + OH --> PSD1 + ETHP                                                                      ', &
     '      PAR + OH --> 0.012 ALK1 + PSD1 + RO2                                                          ', &
     '     HCHO + OH --> PSD1 + CO + HO2                                                                  ', &
     '    HCHO + NO3 --> HNO3 + CO + HO2                                                                  ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_2 = (/ &
     '     ALD2 + OH --> PSD1 + C2O3                                                                      ', &
     '    ALD2 + NO3 --> HNO3 + C2O3                                                                      ', &
     '     AONE + OH --> PSD1 + ANO2                                                                      ', &
     '     MGLY + OH --> PSD1 + XO2 + C2O3                                                                ', &
     '    MGLY + NO3 --> HNO3 + CO + C2O3                                                                 ', &
     '      ETH + O3 --> 0.52 HCOOH + 0.24 CO + HCHO + 0.12 OH + 0.22 HO2                                 ', &
     '      ETH + OH --> PSD1 + 1.56 HCHO + XO2 + 0.22 ALD2 + HO2                                         ', &
     '     OLET + O3 --> 0.22 HCOOH + 0.09 RCOOH + 0.008 OLE1 + 0.06 CH4 + 0.01 C2H6 + 1.06 XPAR + 0.03 CH', &
     '     OLEI + O3 --> 0.16 RCOOH + 0.008 OLE1 + 0.08 CH4 + 0.01 C2H6 + 2.26 XPAR + 0.04 CH3OH + 0.3 CO ', &
     '     OLET + OH --> 0.008 OLE1 + PSD1 + XPAR + HCHO + XO2 + ALD2 + HO2                               ', &
     '     OLEI + OH --> 0.008 OLE1 + PSD1 + 2.23 XPAR + XO2 + 0.23 AONE + 1.77 ALD2 + HO2                ', &
     '    OLET + NO3 --> 0.008 OLE1 + NAP                                                                 ', &
     '    OLEI + NO3 --> 0.008 OLE1 + NAP                                                                 ', &
     '      TOL + OH --> 0.039 ARO1 + 0.108 ARO2 + PSD1 + 0.8 TO2 + 0.12 CRES + 0.08 XO2 + 0.2 HO2        ', &
     '      XYL + OH --> 0.039 ARO1 + 0.108 ARO2 + PSD1 + 0.45 TO2 + 0.05 CRES + 1.1 PAR + 0.5 XO2 + 0.8 M', &
     '      TO2 + NO --> 0.95 OPEN + 0.05 ONIT + 0.95 NO2 + 0.95 HO2                                      ', &
     '     CRES + OH --> 0.039 ARO1 + 0.108 ARO2 + PSD1 + 0.4 CRO + 0.3 OPEN + 0.6 XO2 + 0.6 HO2          ', &
     '    CRES + NO3 --> 0.039 ARO1 + 0.108 ARO2 + CRO + HNO3                                             ', &
     '     CRO + NO2 --> ONIT                                                                             ', &
     '     OPEN + OH --> PSD1 + 2 CO + HCHO + XO2 + C2O3 + 2 HO2                                          ', &
     '     OPEN + O3 --> 0.69 CO + 0.7 HCHO + 0.03 XO2 + 0.2 MGLY + 0.03 ALD2 + 0.62 C2O3 + 0.08 OH + 0.76', &
     '     ISOP + OH --> PSD1 + ISOPP + 0.08 XO2                                                          ', &
     '     ISOP + O3 --> 0.39 RCOOH + 0.07 CO + 0.6 HCHO + 0.2 XO2 + 0.15 ALD2 + 0.65 ISOPRD + 0.2 C2O3 + ', &
     '    ISOP + NO3 --> ISOPN                                                                            ', &
     '   ISOPRD + OH --> PSD1 + 0.5 ISOPO2 + 0.2 XO2 + 0.5 C2O3                                           ', &
     '   ISOPRD + O3 --> 0.46 RCOOH + 0.16 CO + 0.15 HCHO + 0.07 XO2 + 0.09 AONE + 0.85 MGLY + 0.02 ALD2 +', &
     '  ISOPRD + NO3 --> 0.07 HNO3 + 0.64 CO + 1.86 PAR + 0.28 HCHO + 0.93 XO2 + 0.28 ALD2 + 0.93 ONIT + 0', &
     '    ISOPP + NO --> 0.18 PAR + 0.63 HCHO + 0.91 ISOPRD + 0.09 ONIT + 0.91 NO2 + 0.91 HO2             ', &
     '    ISOPN + NO --> 1.6 PAR + 0.8 ALD2 + 0.2 ISOPRD + 0.8 ONIT + 1.2 NO2 + 0.8 HO2                   ', &
     '   ISOPO2 + NO --> 0.59 CO + 0.25 HCHO + 0.63 AONE + 0.34 MGLY + 0.55 ALD2 + NO2 + HO2              ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_3 = (/ &
     '   ISOPP + HO2 --> ROOH                                                                             ', &
     '   ISOPN + HO2 --> 2 PAR + ONIT                                                                     ', &
     '  ISOPO2 + HO2 --> ROOH                                                                             ', &
     '   CH3OOH + OH --> PSD1 + 0.3 HCHO + 0.7 CH3O2 + 0.3 OH                                             ', &
     '   ETHOOH + OH --> PSD1 + 0.7 ETHP + 0.3 ALD2 + 0.3 OH                                              ', &
     '     OH + ROOH --> PSD1 + 0.42 XPAR + 0.19 MGLY + 0.04 ALD2 + 0.77 RO2 + 0.23 OH                    ', &
     '     ONIT + OH --> PSD1 + NAP                                                                       ', &
     '    NO2 + C2O3 --> PAN                                                                              ', &
     '           PAN --> NO2 + C2O3                                                                       ', &
     '    CH3OH + OH --> PSD1 + HCHO + HO2                                                                ', &
     '    CH3O2 + NO --> HCHO + NO2 + HO2                                                                 ', &
     '     ETHP + NO --> ALD2 + NO2 + HO2                                                                 ', &
     '      RO2 + NO --> 1.68 XPAR + 0.34 XO2 + 0.62 AONE + 0.08 ETHP + 0.25 ALD2 + 0.16 ONIT + 0.84 NO2 +', &
     '     C2O3 + NO --> CH3O2 + NO2                                                                      ', &
     '     NO + ANO2 --> HCHO + NO2 + C2O3                                                                ', &
     '      NAP + NO --> XPAR + 0.5 HCHO + 0.5 ALD2 + 0.5 ONIT + 1.5 NO2 + 0.5 HO2                        ', &
     '      XO2 + NO --> NO2                                                                              ', &
     '   CH3O2 + NO3 --> HCHO + NO2 + HO2                                                                 ', &
     '    ETHP + NO3 --> ALD2 + NO2 + HO2                                                                 ', &
     '     RO2 + NO3 --> 1.98 XPAR + 0.4 XO2 + 0.74 AONE + 0.1 ETHP + 0.3 ALD2 + NO2 + 0.9 HO2            ', &
     '    C2O3 + NO3 --> CH3O2 + NO2                                                                      ', &
     '    ANO2 + NO3 --> HCHO + NO2 + C2O3                                                                ', &
     '     NAP + NO3 --> XPAR + 0.5 HCHO + 0.5 ALD2 + 0.5 ONIT + 1.5 NO2 + 0.5 HO2                        ', &
     '     XO2 + NO3 --> NO2                                                                              ', &
     '   CH3O2 + HO2 --> CH3OOH                                                                           ', &
     '    ETHP + HO2 --> ETHOOH                                                                           ', &
     '     RO2 + HO2 --> ROOH                                                                             ', &
     '    C2O3 + HO2 --> 0.4 RCOOH + 0.4 O3                                                               ', &
     '    HO2 + ANO2 --> ROOH                                                                             ', &
     '     NAP + HO2 --> ONIT                                                                             ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_4 = (/ &
     '     XO2 + HO2 -->                                                                                  ', &
     '     ANOL + OH --> PSD1 + ALD2 + HO2                                                                ', &
     '    XPAR + PAR -->                                                                                  ', &
     '           HCl --> HCl                                                                              ', &
     '           NH3 --> NH3                                                                              ', &
     '         H2SO4 --> H2SO4                                                                            ', &
     '         CH3O2 --> 0.34 CH3OH + 0.66 HCHO + 0.32 HO2                                                ', &
     '          ETHP --> 0.2 C2H6 + 0.8 ALD2 + 0.6 HO2                                                    ', &
     '           RO2 --> 1.25 XPAR + 0.24 XO2 + 0.57 AONE + 0.06 ETHP + 0.21 ALD2 + 0.54 HO2              ', &
     '          C2O3 --> CH3O2                                                                            ', &
     '          ANO2 --> 0.7 HCHO + 0.15 AONE + 0.15 MGLY + 0.7 C2O3                                      ', &
     '           NAP --> XPAR + 0.5 HCHO + 0.5 ALD2 + 0.5 ONIT + 0.5 NO2                                  ', &
     '         ISOPP --> ISOPRD                                                                           ', &
     '         ISOPN --> 2 PAR + ALD2 + ONIT                                                              ', &
     '        ISOPO2 --> 0.5 AONE + 0.5 ALD2                                                              ', &
     '           XO2 -->                                                                                  ', &
     '      API + OH --> 0.0064 API1 + 0.055 API2 + PSD2                                                  ', &
     '     API + NO3 -->                                                                                  ', &
     '      API + O3 --> 0.022 API1 + 0.19 API2                                                           ', &
     '      LIM + OH --> 0.037 LIM1 + 0.056 LIM2 + PSD2                                                   ', &
     '     LIM + NO3 -->                                                                                  ', &
     '      LIM + O3 --> 0.13 LIM1 + 0.19 LIM2                                                            ', &
     ' PCG1_B_C + OH --> PCG1_B_C + PSD2                                                                  ', &
     ' PCG1_B_O + OH --> PCG1_B_O + PSD2                                                                  ', &
     'OPCG1_B_C + OH --> PSD2 + OPCG1_B_C                                                                 ', &
     'OPCG1_B_O + OH --> PSD2 + OPCG1_B_O                                                                 ', &
     ' PCG1_F_C + OH --> PCG1_F_C + PSD2                                                                  ', &
     ' PCG1_F_O + OH --> PCG1_F_O + PSD2                                                                  ', &
     'OPCG1_F_C + OH --> PSD2 + OPCG1_F_C                                                                 ', &
     'OPCG1_F_O + OH --> PSD2 + OPCG1_F_O                                                                 ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_5 = (/ &
     ' PCG2_B_C + OH --> PSD2 + OPCG1_B_C + 0.075 OPCG1_B_O                                               ', &
     ' PCG2_B_O + OH --> PSD2 + OPCG1_B_O                                                                 ', &
     'OPCG2_B_C + OH --> PSD2 + OPCG1_B_C + 0.075 OPCG1_B_O                                               ', &
     'OPCG2_B_O + OH --> PSD2 + OPCG1_B_O                                                                 ', &
     ' PCG3_B_C + OH --> PSD2 + OPCG2_B_C + 0.075 OPCG2_B_O                                               ', &
     ' PCG3_B_O + OH --> PSD2 + OPCG2_B_O                                                                 ', &
     'OPCG3_B_C + OH --> PSD2 + OPCG2_B_C + 0.075 OPCG2_B_O                                               ', &
     'OPCG3_B_O + OH --> PSD2 + OPCG2_B_O                                                                 ', &
     ' PCG4_B_C + OH --> PSD2 + 0.075 OPCG3_B_O + OPCG3_B_C                                               ', &
     ' PCG4_B_O + OH --> PSD2 + OPCG3_B_O                                                                 ', &
     'OPCG4_B_C + OH --> PSD2 + 0.075 OPCG3_B_O + OPCG3_B_C                                               ', &
     'OPCG4_B_O + OH --> PSD2 + OPCG3_B_O                                                                 ', &
     ' PCG5_B_C + OH --> PSD2 + 0.075 OPCG4_B_O + OPCG4_B_C                                               ', &
     ' PCG5_B_O + OH --> PSD2 + OPCG4_B_O                                                                 ', &
     'OPCG5_B_C + OH --> PSD2 + 0.075 OPCG4_B_O + OPCG4_B_C                                               ', &
     'OPCG5_B_O + OH --> PSD2 + OPCG4_B_O                                                                 ', &
     ' PCG6_B_C + OH --> PSD2 + 0.075 OPCG5_B_O + OPCG5_B_C                                               ', &
     ' PCG6_B_O + OH --> PSD2 + OPCG5_B_O                                                                 ', &
     'OPCG6_B_C + OH --> PSD2 + 0.075 OPCG5_B_O + OPCG5_B_C                                               ', &
     'OPCG6_B_O + OH --> PSD2 + OPCG5_B_O                                                                 ', &
     ' PCG7_B_C + OH --> PSD2 + 0.075 OPCG6_B_O + OPCG6_B_C                                               ', &
     ' PCG7_B_O + OH --> PSD2 + OPCG6_B_O                                                                 ', &
     'OPCG7_B_C + OH --> PSD2 + 0.075 OPCG6_B_O + OPCG6_B_C                                               ', &
     'OPCG7_B_O + OH --> PSD2 + OPCG6_B_O                                                                 ', &
     ' PCG8_B_C + OH --> PSD2 + 0.075 OPCG7_B_O + OPCG7_B_C                                               ', &
     ' PCG8_B_O + OH --> PSD2 + OPCG7_B_O                                                                 ', &
     'OPCG8_B_C + OH --> PSD2 + 0.075 OPCG7_B_O + OPCG7_B_C                                               ', &
     'OPCG8_B_O + OH --> PSD2 + OPCG7_B_O                                                                 ', &
     ' PCG9_B_C + OH --> PSD2 + 0.075 OPCG8_B_O + OPCG8_B_C                                               ', &
     ' PCG9_B_O + OH --> PSD2 + OPCG8_B_O                                                                 ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_6 = (/ &
     ' PCG2_F_C + OH --> PSD2 + OPCG1_F_C + 0.075 OPCG1_F_O                                               ', &
     ' PCG2_F_O + OH --> PSD2 + OPCG1_F_O                                                                 ', &
     'OPCG2_F_C + OH --> PSD2 + OPCG1_F_C + 0.075 OPCG1_F_O                                               ', &
     'OPCG2_F_O + OH --> PSD2 + OPCG1_F_O                                                                 ', &
     ' PCG3_F_C + OH --> PSD2 + OPCG2_F_C + 0.075 OPCG2_F_O                                               ', &
     ' PCG3_F_O + OH --> PSD2 + OPCG2_F_O                                                                 ', &
     'OPCG3_F_C + OH --> PSD2 + OPCG2_F_C + 0.075 OPCG2_F_O                                               ', &
     'OPCG3_F_O + OH --> PSD2 + OPCG2_F_O                                                                 ', &
     ' PCG4_F_C + OH --> PSD2 + 0.075 OPCG3_F_O + OPCG3_F_C                                               ', &
     ' PCG4_F_O + OH --> PSD2 + OPCG3_F_O                                                                 ', &
     'OPCG4_F_C + OH --> PSD2 + 0.075 OPCG3_F_O + OPCG3_F_C                                               ', &
     'OPCG4_F_O + OH --> PSD2 + OPCG3_F_O                                                                 ', &
     ' PCG5_F_C + OH --> PSD2 + 0.075 OPCG4_F_O + OPCG4_F_C                                               ', &
     ' PCG5_F_O + OH --> PSD2 + OPCG4_F_O                                                                 ', &
     'OPCG5_F_C + OH --> PSD2 + 0.075 OPCG4_F_O + OPCG4_F_C                                               ', &
     'OPCG5_F_O + OH --> PSD2 + OPCG4_F_O                                                                 ', &
     ' PCG6_F_C + OH --> PSD2 + 0.075 OPCG5_F_O + OPCG5_F_C                                               ', &
     ' PCG6_F_O + OH --> PSD2 + OPCG5_F_O                                                                 ', &
     'OPCG6_F_C + OH --> PSD2 + 0.075 OPCG5_F_O + OPCG5_F_C                                               ', &
     'OPCG6_F_O + OH --> PSD2 + OPCG5_F_O                                                                 ', &
     ' PCG7_F_C + OH --> PSD2 + 0.075 OPCG6_F_O + OPCG6_F_C                                               ', &
     ' PCG7_F_O + OH --> PSD2 + OPCG6_F_O                                                                 ', &
     'OPCG7_F_C + OH --> PSD2 + 0.075 OPCG6_F_O + OPCG6_F_C                                               ', &
     'OPCG7_F_O + OH --> PSD2 + OPCG6_F_O                                                                 ', &
     ' PCG8_F_C + OH --> PSD2 + 0.075 OPCG7_F_O + OPCG7_F_C                                               ', &
     ' PCG8_F_O + OH --> PSD2 + OPCG7_F_O                                                                 ', &
     'OPCG8_F_C + OH --> PSD2 + 0.075 OPCG7_F_O + OPCG7_F_C                                               ', &
     'OPCG8_F_O + OH --> PSD2 + OPCG7_F_O                                                                 ', &
     ' PCG9_F_C + OH --> PSD2 + 0.075 OPCG8_F_O + OPCG8_F_C                                               ', &
     ' PCG9_F_O + OH --> PSD2 + OPCG8_F_O                                                                 ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(210) :: EQN_NAMES = (/&
    EQN_NAMES_0, EQN_NAMES_1, EQN_NAMES_2, EQN_NAMES_3, EQN_NAMES_4, &
    EQN_NAMES_5, EQN_NAMES_6 /)

! INLINED global variables

! End INLINED global variables


END MODULE cbmz_mosaic_8bin_vbs9_Monitor
