! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Parameter Module File
! 
! Generated by KPP-2.1 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : saprc99_mosaic_4bin_vbs9_Parameters.f90
! Time                 : Mon Feb 27 11:09:02 2017
! Working directory    : /data/ksetigui/setigui/WRFV3_171015/chem/KPP/mechanisms/saprc99_mosaic_4bin_vbs9
! Equation file        : saprc99_mosaic_4bin_vbs9.kpp
! Output root filename : saprc99_mosaic_4bin_vbs9
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE saprc99_mosaic_4bin_vbs9_Parameters

  USE saprc99_mosaic_4bin_vbs9_Precision
  PUBLIC
  SAVE


! NSPEC - Number of chemical species
  INTEGER, PARAMETER :: NSPEC = 170 
! NVAR - Number of Variable species
  INTEGER, PARAMETER :: NVAR = 168 
! NVARACT - Number of Active species
  INTEGER, PARAMETER :: NVARACT = 141 
! NFIX - Number of Fixed species
  INTEGER, PARAMETER :: NFIX = 2 
! NREACT - Number of reactions
  INTEGER, PARAMETER :: NREACT = 351 
! NVARST - Starting of variables in conc. vect.
  INTEGER, PARAMETER :: NVARST = 1 
! NFIXST - Starting of fixed in conc. vect.
  INTEGER, PARAMETER :: NFIXST = 169 
! NONZERO - Number of nonzero entries in Jacobian
  INTEGER, PARAMETER :: NONZERO = 1387 
! LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
  INTEGER, PARAMETER :: LU_NONZERO = 1472 
! CNVAR - (NVAR+1) Number of elements in compressed row format
  INTEGER, PARAMETER :: CNVAR = 169 
! NLOOKAT - Number of species to look at
  INTEGER, PARAMETER :: NLOOKAT = 0 
! NMONITOR - Number of species to monitor
  INTEGER, PARAMETER :: NMONITOR = 0 
! NMASS - Number of atoms to check mass balance
  INTEGER, PARAMETER :: NMASS = 1 
! PI - Value of pi
  REAL(kind=dp), PARAMETER :: PI = 3.14159265358979 

! Index declaration for variable species in C and VAR
!   VAR(ind_spc) = C(ind_spc)

  INTEGER, PARAMETER :: ind_H2SO4 = 1 
  INTEGER, PARAMETER :: ind_CO2 = 2 
  INTEGER, PARAMETER :: ind_PCG1_B_C = 3 
  INTEGER, PARAMETER :: ind_PCG1_B_O = 4 
  INTEGER, PARAMETER :: ind_PCG1_F_C = 5 
  INTEGER, PARAMETER :: ind_PCG1_F_O = 6 
  INTEGER, PARAMETER :: ind_HCOOH = 7 
  INTEGER, PARAMETER :: ind_CCO_OH = 8 
  INTEGER, PARAMETER :: ind_RCO_OH = 9 
  INTEGER, PARAMETER :: ind_CCO_OOH = 10 
  INTEGER, PARAMETER :: ind_RCO_OOH = 11 
  INTEGER, PARAMETER :: ind_XN = 12 
  INTEGER, PARAMETER :: ind_XC = 13 
  INTEGER, PARAMETER :: ind_NUME = 14 
  INTEGER, PARAMETER :: ind_DEN = 15 
  INTEGER, PARAMETER :: ind_ANT1_c = 16 
  INTEGER, PARAMETER :: ind_ANT2_c = 17 
  INTEGER, PARAMETER :: ind_ANT3_c = 18 
  INTEGER, PARAMETER :: ind_ANT4_c = 19 
  INTEGER, PARAMETER :: ind_ANT1_o = 20 
  INTEGER, PARAMETER :: ind_ANT2_o = 21 
  INTEGER, PARAMETER :: ind_ANT3_o = 22 
  INTEGER, PARAMETER :: ind_ANT4_o = 23 
  INTEGER, PARAMETER :: ind_BIOG1_c = 24 
  INTEGER, PARAMETER :: ind_BIOG2_c = 25 
  INTEGER, PARAMETER :: ind_BIOG3_c = 26 
  INTEGER, PARAMETER :: ind_BIOG4_c = 27 
  INTEGER, PARAMETER :: ind_BIOG1_o = 28 
  INTEGER, PARAMETER :: ind_BIOG2_o = 29 
  INTEGER, PARAMETER :: ind_BIOG3_o = 30 
  INTEGER, PARAMETER :: ind_BIOG4_o = 31 
  INTEGER, PARAMETER :: ind_PSD1 = 32 
  INTEGER, PARAMETER :: ind_PSD2 = 33 
  INTEGER, PARAMETER :: ind_OPCG1_B_O = 34 
  INTEGER, PARAMETER :: ind_PCG2_B_O = 35 
  INTEGER, PARAMETER :: ind_OPCG2_B_O = 36 
  INTEGER, PARAMETER :: ind_PCG3_B_O = 37 
  INTEGER, PARAMETER :: ind_OPCG3_B_O = 38 
  INTEGER, PARAMETER :: ind_PCG4_B_O = 39 
  INTEGER, PARAMETER :: ind_OPCG4_B_O = 40 
  INTEGER, PARAMETER :: ind_PCG5_B_O = 41 
  INTEGER, PARAMETER :: ind_OPCG5_B_O = 42 
  INTEGER, PARAMETER :: ind_PCG6_B_O = 43 
  INTEGER, PARAMETER :: ind_OPCG6_B_O = 44 
  INTEGER, PARAMETER :: ind_PCG7_B_O = 45 
  INTEGER, PARAMETER :: ind_OPCG7_B_O = 46 
  INTEGER, PARAMETER :: ind_PCG8_B_O = 47 
  INTEGER, PARAMETER :: ind_OPCG8_B_O = 48 
  INTEGER, PARAMETER :: ind_PCG9_B_O = 49 
  INTEGER, PARAMETER :: ind_OPCG1_F_O = 50 
  INTEGER, PARAMETER :: ind_PCG2_F_O = 51 
  INTEGER, PARAMETER :: ind_OPCG2_F_O = 52 
  INTEGER, PARAMETER :: ind_PCG3_F_O = 53 
  INTEGER, PARAMETER :: ind_OPCG3_F_O = 54 
  INTEGER, PARAMETER :: ind_PCG4_F_O = 55 
  INTEGER, PARAMETER :: ind_OPCG4_F_O = 56 
  INTEGER, PARAMETER :: ind_PCG5_F_O = 57 
  INTEGER, PARAMETER :: ind_OPCG5_F_O = 58 
  INTEGER, PARAMETER :: ind_PCG6_F_O = 59 
  INTEGER, PARAMETER :: ind_OPCG6_F_O = 60 
  INTEGER, PARAMETER :: ind_PCG7_F_O = 61 
  INTEGER, PARAMETER :: ind_OPCG7_F_O = 62 
  INTEGER, PARAMETER :: ind_PCG8_F_O = 63 
  INTEGER, PARAMETER :: ind_OPCG8_F_O = 64 
  INTEGER, PARAMETER :: ind_PCG9_F_O = 65 
  INTEGER, PARAMETER :: ind_PCG2_B_C = 66 
  INTEGER, PARAMETER :: ind_PCG3_B_C = 67 
  INTEGER, PARAMETER :: ind_PCG4_B_C = 68 
  INTEGER, PARAMETER :: ind_PCG5_B_C = 69 
  INTEGER, PARAMETER :: ind_PCG6_B_C = 70 
  INTEGER, PARAMETER :: ind_PCG7_B_C = 71 
  INTEGER, PARAMETER :: ind_PCG8_B_C = 72 
  INTEGER, PARAMETER :: ind_PCG9_B_C = 73 
  INTEGER, PARAMETER :: ind_OPCG1_B_C = 74 
  INTEGER, PARAMETER :: ind_OPCG2_B_C = 75 
  INTEGER, PARAMETER :: ind_OPCG3_B_C = 76 
  INTEGER, PARAMETER :: ind_OPCG4_B_C = 77 
  INTEGER, PARAMETER :: ind_OPCG5_B_C = 78 
  INTEGER, PARAMETER :: ind_OPCG6_B_C = 79 
  INTEGER, PARAMETER :: ind_OPCG7_B_C = 80 
  INTEGER, PARAMETER :: ind_OPCG8_B_C = 81 
  INTEGER, PARAMETER :: ind_PCG2_F_C = 82 
  INTEGER, PARAMETER :: ind_PCG3_F_C = 83 
  INTEGER, PARAMETER :: ind_PCG4_F_C = 84 
  INTEGER, PARAMETER :: ind_PCG5_F_C = 85 
  INTEGER, PARAMETER :: ind_PCG6_F_C = 86 
  INTEGER, PARAMETER :: ind_PCG7_F_C = 87 
  INTEGER, PARAMETER :: ind_PCG8_F_C = 88 
  INTEGER, PARAMETER :: ind_PCG9_F_C = 89 
  INTEGER, PARAMETER :: ind_O1D = 90 
  INTEGER, PARAMETER :: ind_OPCG1_F_C = 91 
  INTEGER, PARAMETER :: ind_OPCG2_F_C = 92 
  INTEGER, PARAMETER :: ind_OPCG3_F_C = 93 
  INTEGER, PARAMETER :: ind_OPCG4_F_C = 94 
  INTEGER, PARAMETER :: ind_OPCG5_F_C = 95 
  INTEGER, PARAMETER :: ind_OPCG6_F_C = 96 
  INTEGER, PARAMETER :: ind_OPCG7_F_C = 97 
  INTEGER, PARAMETER :: ind_OPCG8_F_C = 98 
  INTEGER, PARAMETER :: ind_CH4 = 99 
  INTEGER, PARAMETER :: ind_SO2 = 100 
  INTEGER, PARAMETER :: ind_C2H6 = 101 
  INTEGER, PARAMETER :: ind_PAN2 = 102 
  INTEGER, PARAMETER :: ind_MA_PAN = 103 
  INTEGER, PARAMETER :: ind_PAN = 104 
  INTEGER, PARAMETER :: ind_PBZN = 105 
  INTEGER, PARAMETER :: ind_H2O2 = 106 
  INTEGER, PARAMETER :: ind_C3H8 = 107 
  INTEGER, PARAMETER :: ind_ETOH = 108 
  INTEGER, PARAMETER :: ind_BACL = 109 
  INTEGER, PARAMETER :: ind_N2O5 = 110 
  INTEGER, PARAMETER :: ind_HONO = 111 
  INTEGER, PARAMETER :: ind_ALK5 = 112 
  INTEGER, PARAMETER :: ind_ALK3 = 113 
  INTEGER, PARAMETER :: ind_TBU_O = 114 
  INTEGER, PARAMETER :: ind_ARO2 = 115 
  INTEGER, PARAMETER :: ind_COOH = 116 
  INTEGER, PARAMETER :: ind_HOCOO = 117 
  INTEGER, PARAMETER :: ind_BZNO2_O = 118 
  INTEGER, PARAMETER :: ind_HNO4 = 119 
  INTEGER, PARAMETER :: ind_MEOH = 120 
  INTEGER, PARAMETER :: ind_ARO1 = 121 
  INTEGER, PARAMETER :: ind_DCB2 = 122 
  INTEGER, PARAMETER :: ind_DCB3 = 123 
  INTEGER, PARAMETER :: ind_CRES = 124 
  INTEGER, PARAMETER :: ind_ALK4 = 125 
  INTEGER, PARAMETER :: ind_C2H2 = 126 
  INTEGER, PARAMETER :: ind_DCB1 = 127 
  INTEGER, PARAMETER :: ind_NPHE = 128 
  INTEGER, PARAMETER :: ind_ROOH = 129 
  INTEGER, PARAMETER :: ind_BALD = 130 
  INTEGER, PARAMETER :: ind_PHEN = 131 
  INTEGER, PARAMETER :: ind_MGLY = 132 
  INTEGER, PARAMETER :: ind_CO = 133 
  INTEGER, PARAMETER :: ind_HNO3 = 134 
  INTEGER, PARAMETER :: ind_ETHENE = 135 
  INTEGER, PARAMETER :: ind_ACET = 136 
  INTEGER, PARAMETER :: ind_C3H6 = 137 
  INTEGER, PARAMETER :: ind_BZ_O = 138 
  INTEGER, PARAMETER :: ind_OLE1 = 139 
  INTEGER, PARAMETER :: ind_ISOPRENE = 140 
  INTEGER, PARAMETER :: ind_R2O2 = 141 
  INTEGER, PARAMETER :: ind_METHACRO = 142 
  INTEGER, PARAMETER :: ind_SESQ = 143 
  INTEGER, PARAMETER :: ind_TERP = 144 
  INTEGER, PARAMETER :: ind_GLY = 145 
  INTEGER, PARAMETER :: ind_ISOPROD = 146 
  INTEGER, PARAMETER :: ind_OLE2 = 147 
  INTEGER, PARAMETER :: ind_MVK = 148 
  INTEGER, PARAMETER :: ind_CCHO = 149 
  INTEGER, PARAMETER :: ind_HCHO = 150 
  INTEGER, PARAMETER :: ind_RNO3 = 151 
  INTEGER, PARAMETER :: ind_O3P = 152 
  INTEGER, PARAMETER :: ind_RCHO = 153 
  INTEGER, PARAMETER :: ind_MEK = 154 
  INTEGER, PARAMETER :: ind_PROD2 = 155 
  INTEGER, PARAMETER :: ind_O3 = 156 
  INTEGER, PARAMETER :: ind_NO3 = 157 
  INTEGER, PARAMETER :: ind_RO2_N = 158 
  INTEGER, PARAMETER :: ind_MA_RCO3 = 159 
  INTEGER, PARAMETER :: ind_NO = 160 
  INTEGER, PARAMETER :: ind_HO2 = 161 
  INTEGER, PARAMETER :: ind_RCO_O2 = 162 
  INTEGER, PARAMETER :: ind_CCO_O2 = 163 
  INTEGER, PARAMETER :: ind_BZCO_O2 = 164 
  INTEGER, PARAMETER :: ind_OH = 165 
  INTEGER, PARAMETER :: ind_RO2_R = 166 
  INTEGER, PARAMETER :: ind_NO2 = 167 
  INTEGER, PARAMETER :: ind_C_O2 = 168 

! Index declaration for fixed species in C
!   C(ind_spc)

  INTEGER, PARAMETER :: ind_H2O = 169 
  INTEGER, PARAMETER :: ind_M = 170 

! Index declaration for fixed species in FIX
!    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)

  INTEGER, PARAMETER :: indf_H2O = 1 
  INTEGER, PARAMETER :: indf_M = 2 

END MODULE saprc99_mosaic_4bin_vbs9_Parameters

