! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Parameter Module File
! 
! Generated by KPP-2.1 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : saprc99_mosaic_8bin_vbs2_aq_Parameters.f90
! Time                 : Mon Feb 27 11:09:03 2017
! Working directory    : /data/ksetigui/setigui/WRFV3_171015/chem/KPP/mechanisms/saprc99_mosaic_8bin_vbs2_aq
! Equation file        : saprc99_mosaic_8bin_vbs2_aq.kpp
! Output root filename : saprc99_mosaic_8bin_vbs2_aq
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE saprc99_mosaic_8bin_vbs2_aq_Parameters

  USE saprc99_mosaic_8bin_vbs2_aq_Precision
  PUBLIC
  SAVE


! NSPEC - Number of chemical species
  INTEGER, PARAMETER :: NSPEC = 94 
! NVAR - Number of Variable species
  INTEGER, PARAMETER :: NVAR = 92 
! NVARACT - Number of Active species
  INTEGER, PARAMETER :: NVARACT = 72 
! NFIX - Number of Fixed species
  INTEGER, PARAMETER :: NFIX = 2 
! NREACT - Number of reactions
  INTEGER, PARAMETER :: NREACT = 255 
! NVARST - Starting of variables in conc. vect.
  INTEGER, PARAMETER :: NVARST = 1 
! NFIXST - Starting of fixed in conc. vect.
  INTEGER, PARAMETER :: NFIXST = 93 
! NONZERO - Number of nonzero entries in Jacobian
  INTEGER, PARAMETER :: NONZERO = 1024 
! LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
  INTEGER, PARAMETER :: LU_NONZERO = 1109 
! CNVAR - (NVAR+1) Number of elements in compressed row format
  INTEGER, PARAMETER :: CNVAR = 93 
! NLOOKAT - Number of species to look at
  INTEGER, PARAMETER :: NLOOKAT = 0 
! NMONITOR - Number of species to monitor
  INTEGER, PARAMETER :: NMONITOR = 0 
! NMASS - Number of atoms to check mass balance
  INTEGER, PARAMETER :: NMASS = 1 
! PI - Value of pi
  REAL(kind=dp), PARAMETER :: PI = 3.14159265358979 

! Index declaration for variable species in C and VAR
!   VAR(ind_spc) = C(ind_spc)

  INTEGER, PARAMETER :: ind_H2SO4 = 1 
  INTEGER, PARAMETER :: ind_HCOOH = 2 
  INTEGER, PARAMETER :: ind_CCO_OH = 3 
  INTEGER, PARAMETER :: ind_RCO_OH = 4 
  INTEGER, PARAMETER :: ind_CO2 = 5 
  INTEGER, PARAMETER :: ind_CCO_OOH = 6 
  INTEGER, PARAMETER :: ind_RCO_OOH = 7 
  INTEGER, PARAMETER :: ind_XN = 8 
  INTEGER, PARAMETER :: ind_XC = 9 
  INTEGER, PARAMETER :: ind_NUME = 10 
  INTEGER, PARAMETER :: ind_DEN = 11 
  INTEGER, PARAMETER :: ind_ANT1_c = 12 
  INTEGER, PARAMETER :: ind_ANT2_c = 13 
  INTEGER, PARAMETER :: ind_ANT3_c = 14 
  INTEGER, PARAMETER :: ind_ANT4_c = 15 
  INTEGER, PARAMETER :: ind_BIOG1_c = 16 
  INTEGER, PARAMETER :: ind_BIOG2_c = 17 
  INTEGER, PARAMETER :: ind_BIOG3_c = 18 
  INTEGER, PARAMETER :: ind_BIOG4_c = 19 
  INTEGER, PARAMETER :: ind_PSD1 = 20 
  INTEGER, PARAMETER :: ind_O1D = 21 
  INTEGER, PARAMETER :: ind_CH4 = 22 
  INTEGER, PARAMETER :: ind_C2H6 = 23 
  INTEGER, PARAMETER :: ind_PAN = 24 
  INTEGER, PARAMETER :: ind_PAN2 = 25 
  INTEGER, PARAMETER :: ind_PBZN = 26 
  INTEGER, PARAMETER :: ind_MA_PAN = 27 
  INTEGER, PARAMETER :: ind_H2O2 = 28 
  INTEGER, PARAMETER :: ind_C3H8 = 29 
  INTEGER, PARAMETER :: ind_BACL = 30 
  INTEGER, PARAMETER :: ind_ETOH = 31 
  INTEGER, PARAMETER :: ind_N2O5 = 32 
  INTEGER, PARAMETER :: ind_SO2 = 33 
  INTEGER, PARAMETER :: ind_DMS = 34 
  INTEGER, PARAMETER :: ind_HONO = 35 
  INTEGER, PARAMETER :: ind_ALK3 = 36 
  INTEGER, PARAMETER :: ind_TBU_O = 37 
  INTEGER, PARAMETER :: ind_ALK5 = 38 
  INTEGER, PARAMETER :: ind_ARO2 = 39 
  INTEGER, PARAMETER :: ind_COOH = 40 
  INTEGER, PARAMETER :: ind_HOCOO = 41 
  INTEGER, PARAMETER :: ind_BZNO2_O = 42 
  INTEGER, PARAMETER :: ind_HNO4 = 43 
  INTEGER, PARAMETER :: ind_MEOH = 44 
  INTEGER, PARAMETER :: ind_ARO1 = 45 
  INTEGER, PARAMETER :: ind_DCB3 = 46 
  INTEGER, PARAMETER :: ind_DCB2 = 47 
  INTEGER, PARAMETER :: ind_CRES = 48 
  INTEGER, PARAMETER :: ind_ALK4 = 49 
  INTEGER, PARAMETER :: ind_DCB1 = 50 
  INTEGER, PARAMETER :: ind_C2H2 = 51 
  INTEGER, PARAMETER :: ind_ROOH = 52 
  INTEGER, PARAMETER :: ind_NPHE = 53 
  INTEGER, PARAMETER :: ind_BALD = 54 
  INTEGER, PARAMETER :: ind_PHEN = 55 
  INTEGER, PARAMETER :: ind_MGLY = 56 
  INTEGER, PARAMETER :: ind_CO = 57 
  INTEGER, PARAMETER :: ind_HNO3 = 58 
  INTEGER, PARAMETER :: ind_ETHENE = 59 
  INTEGER, PARAMETER :: ind_ACET = 60 
  INTEGER, PARAMETER :: ind_C3H6 = 61 
  INTEGER, PARAMETER :: ind_BZ_O = 62 
  INTEGER, PARAMETER :: ind_OLE1 = 63 
  INTEGER, PARAMETER :: ind_ISOPRENE = 64 
  INTEGER, PARAMETER :: ind_R2O2 = 65 
  INTEGER, PARAMETER :: ind_METHACRO = 66 
  INTEGER, PARAMETER :: ind_TERP = 67 
  INTEGER, PARAMETER :: ind_SESQ = 68 
  INTEGER, PARAMETER :: ind_GLY = 69 
  INTEGER, PARAMETER :: ind_ISOPROD = 70 
  INTEGER, PARAMETER :: ind_OLE2 = 71 
  INTEGER, PARAMETER :: ind_MVK = 72 
  INTEGER, PARAMETER :: ind_CCHO = 73 
  INTEGER, PARAMETER :: ind_HCHO = 74 
  INTEGER, PARAMETER :: ind_RNO3 = 75 
  INTEGER, PARAMETER :: ind_O3P = 76 
  INTEGER, PARAMETER :: ind_RCHO = 77 
  INTEGER, PARAMETER :: ind_MEK = 78 
  INTEGER, PARAMETER :: ind_PROD2 = 79 
  INTEGER, PARAMETER :: ind_O3 = 80 
  INTEGER, PARAMETER :: ind_RCO_O2 = 81 
  INTEGER, PARAMETER :: ind_NO2 = 82 
  INTEGER, PARAMETER :: ind_HO2 = 83 
  INTEGER, PARAMETER :: ind_BZCO_O2 = 84 
  INTEGER, PARAMETER :: ind_C_O2 = 85 
  INTEGER, PARAMETER :: ind_NO3 = 86 
  INTEGER, PARAMETER :: ind_NO = 87 
  INTEGER, PARAMETER :: ind_RO2_R = 88 
  INTEGER, PARAMETER :: ind_RO2_N = 89 
  INTEGER, PARAMETER :: ind_CCO_O2 = 90 
  INTEGER, PARAMETER :: ind_MA_RCO3 = 91 
  INTEGER, PARAMETER :: ind_OH = 92 

! Index declaration for fixed species in C
!   C(ind_spc)

  INTEGER, PARAMETER :: ind_H2O = 93 
  INTEGER, PARAMETER :: ind_M = 94 

! Index declaration for fixed species in FIX
!    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)

  INTEGER, PARAMETER :: indf_H2O = 1 
  INTEGER, PARAMETER :: indf_M = 2 

END MODULE saprc99_mosaic_8bin_vbs2_aq_Parameters

